server:
  port : 8081
  
#spring:#  security:#    user:#      name: kevin
#      password: dummy

jwt:
  signing.key.secret: mySecret
  get.token.uri: /authenticate
  refresh.token.uri: /refresh
  http.request.header: Authorization
  token.expiration.in.seconds: 604800